### ISSUE TITLE
benchmark result

### ISSUE THREAD

**Issue by skyzh** [skyzh/uring-positioned-io#2]
![write_waterfall_mmap](https://user-images.githubusercontent.com/4198311/106277551-4a776880-6274-11eb-9f2c-3981685f537f.png)
![write_waterfall_uring](https://user-images.githubusercontent.com/4198311/106277572-53683a00-6274-11eb-9e3e-91d119b6e663.png)

**Comment by skyzh** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/4198311/106277755-8ca0aa00-6274-11eb-804d-b8ab1eac4de2.png">
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/4198311/106277796-9b875c80-6274-11eb-8396-a9dbbb319f8a.png">

Left 1 minute: mmap. Right 1 minute: io_uring.

**Comment by skyzh** [comment]
![write_waterfall_16](https://user-images.githubusercontent.com/4198311/106278601-f66d8380-6275-11eb-9ba4-442be462800b.png)
![write_waterfall_mmap_random](https://user-images.githubusercontent.com/4198311/106279197-03d73d80-6277-11eb-8d17-b06da04c2c3a.png)
![write_waterfall_16_new](https://user-images.githubusercontent.com/4198311/106279470-6d574c00-6277-11eb-87aa-b988e2bfed4f.png)

**Comment by skyzh** [comment]
![uring](https://user-images.githubusercontent.com/4198311/106355863-b53ca880-6335-11eb-9dfe-0682aefa1093.png)

![waterfall_mmap_8](https://user-images.githubusercontent.com/4198311/106357357-a14a7400-6340-11eb-89df-72e876855557.png)
![waterfall_mmap_32](https://user-images.githubusercontent.com/4198311/106357361-a5769180-6340-11eb-8a85-80180df69ea8.png)
![waterfall_mmap_512](https://user-images.githubusercontent.com/4198311/106357363-a5769180-6340-11eb-9704-7c97d9a577a6.png)
![waterfall_uring_8](https://user-images.githubusercontent.com/4198311/106357364-a60f2800-6340-11eb-9376-2d66ffa7098f.png)
![waterfall_uring_32](https://user-images.githubusercontent.com/4198311/106357365-a6a7be80-6340-11eb-81e7-945758dd2092.png)
![waterfall_uring_512](https://user-images.githubusercontent.com/4198311/106357366-a6a7be80-6340-11eb-9b7e-ec4ff168962d.png)
![Throughput-2](https://user-images.githubusercontent.com/4198311/106357531-904e3280-6341-11eb-9577-fcd1a487e6db.png)
![p50 Latency (ns)](https://user-images.githubusercontent.com/4198311/106357534-93e1b980-6341-11eb-8974-05575e63b2b7.png)

**Comment by XiaochenCui** [comment]
hi, @skyzh 
I'm doing some research on io_uring and aio, I'm interested in the tools you used for these graphs (especially the disk heatmap graph), is that some existing tools or custom scripts? Thanks.

**Comment by XiaochenCui** [comment]
I guess you use the "Matplotlib" for the "throughput" and "p50 latency" graph
