### ISSUE TITLE
Upload the mmap benchmark

### ISSUE THREAD

**Issue by YjyJeff** [skyzh/uring-positioned-io#6]
Could you also upload the mmap code described in your [blog](https://www.skyzh.dev/posts/articles/2021-01-30-async-random-read-with-rust/)?

**Comment by skyzh** [comment]
The benchmark command is already in README.

```
RUST_LOG=info cargo run -p uring_bench --release -- read_mmap --nf 128 --nb 262144 --dir ~/Work/uring_bench --duration 60 --threads 8
RUST_LOG=info cargo run -p uring_bench --release -- read_mmap --nf 128 --nb 262144 --dir ~/Work/uring_bench --duration 60 --threads 32
```

**Comment by skyzh** [comment]
And you could find source code here https://github.com/skyzh/uring-positioned-io/blob/master/uring_bench/src/main.rs#L355
